myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
]
# To use media files (serving files during development)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

# This will use to identify if multiple apps are availabel.
app_name="post"
urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<slug:slug>", views.post_page, name="page"),
]

users/urls.py
from django.urls import path
from . import views
app_name="users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_user, name="logout"),
]

posts/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(blank=True, default="bird_fallback.jpg")

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django import forms
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        label="Enter Your Name:",
        max_length=255,
        widget=forms.TextInput({"placeholder": "Enter Your Name:"}),
    )
    
    email = forms.EmailField(label="Enter Your Email:", max_length=255)
    
    password1 = forms.CharField(
        label="Password :",
        widget=forms.PasswordInput(
            {"placeholder": "Enter Your Password :", "autocomplete": "username"}
        ),
    )
    password2 = forms.CharField(
        label="Confirm Password :",
        widget=forms.PasswordInput(
            {
                "placeholder": "Enter Your Confirm Password :",
                "autocomplete": "new-pasword",
            }
        ),
    )

    class Meta:
        model = User
        fields = ("username", "email")

    email.widget.attrs.update({"placeholder": "Enter Your Email :"})
    
    
# AuthenticationForm()    
class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label="Enter Your Name:",
        max_length=255,
        widget=forms.TextInput({"placeholder": "Enter Your Name:"}),
    )
    
    password=forms.CharField(
        label="Enter Your Email:",
        max_length=255,
        widget=forms.PasswordInput({
        "placeholder":"Enter Your Password:"
    }))

myproject/views.py
from django.shortcuts import render


def home(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")

posts/views.py
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse


# Create your views here.
def post_list(request):
    posts = Post.objects.all().order_by("-date")
    context = {"posts": posts}
    return render(request, "posts/post_list.html", context)


def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    # post=Post.objects.all().values()
    print("This is my first page:",post)
    return render(request, "posts/post_page.html",{"post":post})

    # return HttpResponse(slug)

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import RegisterForm, LoginForm
from django.contrib.auth import logout, login

# from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/users/login/")
    else:
        form = RegisterForm()
    return render(request, "users/register.html", {"form": form})


def login_view(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            print("This is form.get_user()", form.get_user())
            login(request, form.get_user())
            return redirect("post:post_list")
            # return HttpResponse("Form is submitted.")
    else:
        form = LoginForm()
    return render(request, "users/login.html", {"form": form})


def logout_user(request):
    logout(request)
    return redirect("/")

templates/about.html
{% extends "layout.html" %} 
{% block title %}About{% endblock title %} 
{% block content %}
<h1>About</h1>
<p>Check Out my <a href="/">Home</a> Page</p>
{% endblock content %}

templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock title %} 
{% block content %}
<h1>Home</h1>
<p>Check Out my <a href="/about">About</a> Page</p>
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Django App{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <nav>
      <a href="/" >
        <span role="img" aria-label="Home">🏠️</span>
        </a>|
      <a href="/about">
        <span role="img" aria-label="about">😆️</span>
        </a>|
      <a href="{% url "post:post_list" %}">
        <span role="img" aria-label="Post">📰️</span>
        </a>|
        <a href="{% url "users:register" %}">
          <span role="img" aria-label="Register">🚀️</span>
          </a>|
        {% if not request.user.is_authenticated %}
        <a href="{% url "users:login" %}">
          <span role="img" aria-label="Login" title="Login">🔒</span>
          </a>
        {% else %}
        
        <a href="{% url "users:logout" %}">
          <span role="text" aria-label="Logout" title="Logout">Logout</span>
          </a>
        {% endif %}
    </nav>
    <main>{% block content %}{% endblock content %}</main>
  </body>
</html>