posts/urls.py
from django.urls import path
from . import views

# This will use to identify if multiple apps are availabel.
app_name="post"
urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<slug:slug>", views.post_page, name="page"),
]

posts/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(blank=True, default="bird_fallback.jpg")

    def __str__(self):
        return self.title

posts/views.py
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse


# Create your views here.
def post_list(request):
    posts = Post.objects.all().order_by("-date")
    context = {"posts": posts}
    return render(request, "posts/post_list.html", context)


def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    # post=Post.objects.all().values()
    print("This is my first page:",post)
    return render(request, "posts/post_page.html",{"post":post})

    # return HttpResponse(slug)

posts/templates/posts/post_list.html
{% extends "layout.html" %} {% block title %}Post List{% endblock title %} 
{% block content %}
<section>
  <h1>Posts</h1>
  {% for post in posts%}
  <article class="post">
    <a href="{% url 'post:page' slug=post.slug%}"> <h2>{{post.title}}</h2></a>
    <p>{{post.date}}</p>
    <p>{{post.body}}</p>
  </article>
  {% endfor %}
</section>
{% endblock content %}

posts/templates/posts/post_page.html
{% extends "layout.html" %} 
{% block title %}{{post.title}}{% endblock title %}
{% block content %}
<section>
  <h1>{{post.title}}</h1>
  <img class="banner" src="{{post.banner.url}}" alt="{{post.title}}" />
  <p>{{post.date}}</p>
  <p>{{post.body}}</p>
</section>
{% endblock %}